Update build-kernel-release.yml

diff --git a/.github/workflows/build-kernel-release.yml b/.github/workflows/build-kernel-release.yml
--- a/.github/workflows/build-kernel-release.yml
+++ b/.github/workflows/build-kernel-release.yml
@@ -7,35 +7,20 @@ permissions:
 on:
   workflow_dispatch:
     inputs:
-      runner:
-        description: "Choose runner"
-        required: true
-        type: choice
-        options:
-          - ubuntu-22.04
-          - ubuntu-local
-        default: ubuntu-22.04
-      lto_type:
-        description: "Choose LTO type (full will not run on basic runners)"
-        required: true
-        type: choice
-        options:
-          - full
-          - thin
-          - none
-        default: thin
-      build_a12_5_10:
-        description: 'Build Android 12 5.10 kernel?'
-        required: true
-        type: boolean
-        default: true
       make_release:
         description: 'Do you want to create a release?'
         required: true
         type: boolean
-        default: false
-      next_branch:
-        description: "Choose next branch"
+        default: true
+      kernelsu_variant:
+        description: "Choose KernelSU"
+        required: true
+        type: choice
+        options:
+          - MKSU
+        default: MKSU
+      kernelsu_branch:
+        description: "Choose ksu branch"
         required: true
         type: choice
         options:
@@ -43,67 +28,62 @@ on:
           - Dev
           - Other
         default: Stable
-      next_branch_other:
+      kernelsu_branch_other:
         description: "If 'Other' is selected, specify your custom branch"
         required: false
         type: string  # This input is required if 'Other' is chosen
         default: ""  # Default is empty, but can be filled in if 'Other' is selected
 
 jobs:
-  build-kernel-a12-5-10:
-    uses: ./.github/workflows/build-kernel.yml
+  build-kernel-a13-5-15:
+    uses: ./.github/workflows/kernel-a13-5.15.yml
     secrets: inherit
-    if: ${{ inputs.build_a12_5_10 }}
     with:
-      runner: ${{ inputs.runner }}
-      lto_type: ${{ inputs.lto_type }}
-      next_branch: ${{ inputs.next_branch }}
-      next_branch_other: ${{ inputs.next_branch_other }}
+      kernelsu_variant: ${{ inputs.kernelsu_variant }}
+      kernelsu_branch: ${{ inputs.kernelsu_branch }}
+      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other }}
 
   trigger-release:
     runs-on: ubuntu-latest
     needs:
-        - build-kernel-a12-5-10
+        - build-kernel-a13-5-15
     if: ${{ inputs.make_release }}
     env:
       REPO_OWNER: WildPlusKernel
       REPO_NAME: GKI_KernelSU_SUSFS
-      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
-      RELEASE_NAME: "*TEST BUILD* GKI Kernels With KernelSU & SUSFS v1.5.5 *TEST BUILD*"
+      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      RELEASE_NAME: "*TEST BUILD* GKI Kernels With KernelSU-${{ inputs.kernelsu_variant }} ${{ inputs.kernelsu_branch }} & SUSFS v1.5.5 *TEST BUILD*"
       RELEASE_NOTES: |
-        This release contains KernelSU and SUSFS v1.5.5
-          
-        Module: 
-        -> https://github.com/sidex15/ksu_module_susfs
-            
-        Official Manager:
-        -> https://github.com/tiann/KernelSU
-        
-        Non-Official Managers:
-        -> https://github.com/5ec1cff/KernelSU
+        This release contains KernelSU-${{ inputs.kernelsu_variant }} ${{ inputs.kernelsu_branch }} and SUSFS v1.5.5
         
         Features:
-        [+] KernelSU
-        [+] SUSFS v1.5.5
-        [+] Wireguard Support
-        [+] Maphide LineageOS Detections
-        [+] Futile Maphide for jit-zygote-cache Detections
-        [+] Magic Mount Support
+        -> KernelSU-${{ inputs.kernelsu_variant }}-${{ inputs.kernelsu_branch }}
+        -> SUSFS ඞ v1.5.5 
+        -> Manual Hooks for Better Hiding
+        -> Wireguard Support
+        -> Simple Maphide for LineageOS Detections
+        -> Futile Maphide for jit-zygote-cache Detections
+        -> Magic Mount Support
 
+        Notes:
+        -> SUS SU Mode 2 will show as disabled or not compatble due to non-kprobe hooks and is not needed anymore!
+
+        Module: 
+        -> https://github.com/sidex15/ksu_module_susfs
+        
     steps:
       # Checkout the code
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Determine the branch for KernelSU
+      - name: Determine the branch for KernelSU-${{ inputs.kernelsu_variant }}
+        if: ${{ inputs.kernelsu_variant == 'MKSU' }}
         run: |
           # Determine the branch based on user input
-          if [[ "${{ inputs.next_branch }}" == "Stable" ]]; then
-            BRANCH="Stable"
-          elif [[ "${{ inputs.next_branch }}" == "Dev" ]]; then
-            BRANCH="next"
-          elif [[ "${{ inputs.next_branch }}" == "Other" && -n "${{ inputs.next_branch_other }}" ]]; then
-            BRANCH="${{ inputs.next_branch_other }}"
+          if [[ "${{ inputs.kernelsu_variant }}" == "MKSU" ]]; then
+            BRANCH="main"
+          elif [[ "${{ inputs.kernelsu_branch }}" == "Other" && -n "${{ inputs.kernelsu_branch_other }}" ]]; then
+            BRANCH="${{ inputs.kernelsu_branch_other }}"
           else
             echo "Error: Custom branch not provided for 'Other'" >&2
             exit 1
@@ -112,39 +92,44 @@ jobs:
           # Store the selected branch in GITHUB_ENV
           echo "KSU_BRANCH=$BRANCH" >> $GITHUB_ENV
 
-      - name: Get commit hash or tag and generate URL for KernelSU
+      - name: Get commit hash or tag and generate URL for KernelSU-${{ inputs.kernelsu_variant }}
         run: |
-          REPO_URL="https://github.com/5ec1cff/KernelSU.git"
-          BRANCH="${{ env.KSU_BRANCH }}"
+          if [ "${{ inputs.kernelsu_variant }}" == "MKSU" ]; then
+            echo "This is the MKSU variant"
+            REPO_URL="https://github.com/5ec1cff/KernelSU.git"
+            REPO_URL2="5ec1cff/KernelSU"
+          else
+            echo "Unknown variant"
+          fi
           
-          if [[ "$BRANCH" == "Stable" ]]; then
+          if [[ "${{ inputs.kernelsu_branch }}" == "Stable" && "${{ inputs.kernelsu_variant }}" != "MKSU" ]]; then
             # Fetch the latest tag
             TAG=$(git ls-remote --tags --sort=-v:refname $REPO_URL | grep -o 'refs/tags/.*' | cut -d'/' -f3 | head -n1)
             if [[ -z "$TAG" ]]; then
-              echo "Error: Could not fetch latest tag for KernelSU" >&2
+              echo "Error: Could not fetch latest tag for Stable" >&2
               exit 1
             fi
             KSU_REF=$TAG
-            KSU_URL="https://github.com/5ec1cff/KernelSU/releases/tag/$TAG"
+            KSU_URL="https://github.com/$REPO_URL2/releases/tag/$TAG"
 
-          elif [[ "$BRANCH" == "next" ]]; then
+          elif [[ "${{ inputs.kernelsu_branch }}" == "Dev" || "${{ inputs.kernelsu_variant }}" == "MKSU" ]]; then
             # Fetch the latest commit from "next" branch
-            COMMIT_HASH=$(git ls-remote $REPO_URL refs/heads/$BRANCH | awk '{ print $1 }')
+            COMMIT_HASH=$(git ls-remote $REPO_URL refs/heads/$KSU_BRANCH | awk '{ print $1 }')
             if [[ -z "$COMMIT_HASH" ]]; then
-              echo "Error: Could not fetch latest commit for KernelSU Dev" >&2
+              echo "Error: Could not fetch latest commit for Dev" >&2
               exit 1
             fi
             KSU_REF=$COMMIT_HASH
-            KSU_URL="https://github.com/5ec1cff/KernelSU/commit/$COMMIT_HASH"
+            KSU_URL="https://github.com/$REPO_URL2/commit/$COMMIT_HASH"
 
           else
-            # Fetch the specific tag for the custom branch
-            TAG=$BRANCH
+            # Fetch the specific tag
+            TAG=${{ inputs.kernelsu_branch_other }}
             if git ls-remote --tags $REPO_URL | grep -q "refs/tags/$TAG"; then
               KSU_REF=$TAG
-              KSU_URL="https://github.com/5ec1cff/KernelSU/releases/tag/$TAG"
+              KSU_URL="https://github.com/$REPO_URL2/releases/tag/$TAG"
             else
-              echo "Error: Specified tag '$TAG' not found in KernelSU" >&2
+              echo "Error: Specified tag '$TAG' not found in KernelSU-Next" >&2
               exit 1
             fi
           fi
@@ -161,7 +146,7 @@ jobs:
           GITLAB_REPO="susfs4ksu"
 
           declare -A BRANCH_MAP=(
-            ["gki_android12_5_10"]="gki-android12-5.10"
+            ["gki_android13_5_15"]="gki-android13-5.15"
           )
 
           for var_name in "${!BRANCH_MAP[@]}"; do
@@ -178,30 +163,47 @@ jobs:
               echo "COMMIT_URL_${var_name}=$COMMIT_URL" >> "$GITHUB_ENV"
             fi
           done
+
+      - name: Append Commit Hashes & Links to `RELEASE_NOTES` & Append KernelSU Reference to `RELEASE_NOTES`
+        run: |
+          if [ "${{ inputs.kernelsu_variant }}" == "MKSU" ]; then
+            echo "This is the MKSU variant"
+            echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
+            echo "$RELEASE_NOTES" >> $GITHUB_ENV
+            echo "MKSU Manager:" >> $GITHUB_ENV
+            echo "-> https://github.com/5ec1cff/KernelSU" >> $GITHUB_ENV
+            echo "EOF" >> $GITHUB_ENV
+          else
+            echo "Unknown variant"
+          fi
           
       - name: Append Commit Hashes & Links to `RELEASE_NOTES` & Append KernelSU Reference to `RELEASE_NOTES`
         run: |
           echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
           echo "$RELEASE_NOTES" >> $GITHUB_ENV
           echo "" >> $GITHUB_ENV
-          echo "LTO TYPE: $lto_type" >> $GITHUB_ENV
+          echo "LTO: thin" >> $GITHUB_ENV
           echo "" >> $GITHUB_ENV
-          echo "Commit Hashes & Links:" >> $GITHUB_ENV
-          echo "KernelSU: [$KSU_REF]($KSU_URL)" >> $GITHUB_ENV
-          echo "[SUSFS4KSU](https://gitlab.com/simonpunk/susfs4ksu):" >> $GITHUB_ENV
-          echo "gki-android12-5.10: [$COMMIT_HASH_gki_android12_5_10]($COMMIT_URL_gki_android12_5_10)" >> $GITHUB_ENV
+          echo "Commit Hashes and Links:" >> $GITHUB_ENV
+          echo "KernelSU:" >> $GITHUB_ENV
+          echo "${{ inputs.kernelsu_variant }}-${{ inputs.kernelsu_branch }}: [$KSU_REF]($KSU_URL)" >> $GITHUB_ENV
+          echo "SUSFS4KSU:" >> $GITHUB_ENV
+          echo "gki-android13-5.15: [$COMMIT_HASH_gki_android13_5_15]($COMMIT_URL_gki_android13_5_15)" >> $GITHUB_ENV
+          echo "" >> $GITHUB_ENV
           echo "EOF" >> $GITHUB_ENV
           
       # Get the Latest Tag from GitHub
       - name: Generate and Create New Tag
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
             # Fetch the latest tag from GitHub (this is the latest tag based on the GitHub API)
             LATEST_TAG=$(gh api repos/$REPO_OWNER/$REPO_NAME/tags --jq '.[0].name')
             if [ -z "$LATEST_TAG" ]; then
-              LATEST_TAG="v1.5.5-0"
+              LATEST_TAG="v1.5.5-r0"
             fi
             
-            NEW_TAG=$(echo "$LATEST_TAG" | awk -F- '{suffix=$2; if (!suffix) suffix=0; suffix++; printf "%s-%d", $1, suffix}')
+            NEW_TAG=$(echo "$LATEST_TAG" | awk -F'-r' '{suffix=$2; if (!suffix) suffix=0; suffix++; printf "%s-r%d", $1, suffix}')
     
             # Output the new tag to be used
             echo "New tag: $NEW_TAG"
@@ -211,8 +213,8 @@ jobs:
 
             # Create the tag in the repository
             git tag $NEW_TAG
-            git push origin $NEW_TAG
-
+            git push --tags
+            
       # Download Artifacts for A12 (Only if A12 Build is successful or input is true or empty)
       - name: Download Artifacts
         uses: actions/download-artifact@v4
@@ -241,8 +243,23 @@ jobs:
               echo "Uploading $file..."
               gh release upload ${{ env.NEW_TAG }} "$file"
           done
+
       # Display Files Uploaded
       - name: Display Files Uploaded
         run: |
           echo "GitHub release created with the following files:"
           ls ./downloaded-artifacts/**/*
+
+      - name: send telegram message on push
+        env:
+          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
+          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
+          TELEGRAM_MESSAGE_THREAD_ID: ${{ secrets.TELEGRAM_MESSAGE_THREAD_ID }}
+        run: |
+          curl -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
+            -d "chat_id=$TELEGRAM_CHAT_ID" \
+            -d "message_thread_id=$TELEGRAM_MESSAGE_THREAD_ID" \
+            -d "text=Latest release: 
+            https://github.com/WildPlusKernel/GKI_KernelSU_SUSFS/releases/tag/${{ env.NEW_TAG }}
+            
+            ${{ env.RELEASE_NOTES }}"
